#!/usr/bin/env bash

# script generated by Claude

set -euo pipefail

# ─── Configuration ───────────────────────────────────────────────────────────
BENCH_BIN="./build/bench_ntt"
OUTPUT_CSV="bench_results3.csv"
THREADS=32

N_EXPONENTS=(10 11 12 13 14 15 16 17 18 19 20)
LIMBS=(24 32 48 64 128 256)

# Implementation name -> CLI flags
declare -A IMPL_FLAGS=(
    ["cpu_fast"]="--cpu-fast"
    ["cpu_prod"]="--cpu-prod"
    ["omp_openfhe"]="--openfhe"
    ["gpu_r2"]="--gpu-radix2"
    ["gpu_r4"]="--gpu-radix4"
)

# ─── Preflight check ────────────────────────────────────────────────────────
if [[ ! -x "$BENCH_BIN" ]]; then
    echo "ERROR: $BENCH_BIN not found or not executable." >&2
    exit 1
fi

# ─── Main ────────────────────────────────────────────────────────────────────
echo "Implementation,N,L,Result" > "$OUTPUT_CSV"

total_configs=$(( ${#IMPL_FLAGS[@]} * ${#N_EXPONENTS[@]} * ${#LIMBS[@]} ))
current=0

for impl in "${!IMPL_FLAGS[@]}"; do
    flag="${IMPL_FLAGS[$impl]}"
    for n_exp in "${N_EXPONENTS[@]}"; do
        N=$((1 << n_exp))
        for limbs in "${LIMBS[@]}"; do
            current=$((current + 1))
            echo "[$current/$total_configs] $impl  N=2^${n_exp}=$N  L=$limbs"

            runtime=$("$BENCH_BIN" $flag -N "$n_exp" -L "$limbs" -T "$THREADS" \
                      | grep -oE '[0-9]+(\.[0-9]+)?' | tail -1)

            if [[ -z "$runtime" ]]; then
                echo "  WARNING: no numeric output, writing N/A" >&2
                runtime="N/A"
            fi

            echo "$impl,$N,$limbs,$runtime" >> "$OUTPUT_CSV"
        done
    done
done

echo ""
echo "Done. Results written to $OUTPUT_CSV"
echo "Total configurations: $total_configs"